# Generated by Django 5.1 on 2024-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=20)),
                ('tipo_producto', models.CharField(max_length=10)),
                ('cant_producto', models.CharField(max_length=5)),
                ('metodo_pag', models.CharField(max_length=15)),
                ('proveedor_prod', models.CharField(max_length=15)),
                ('id_proveedor', models.CharField(max_length=15)),
            ],
        ),
    ]
